export const languages = [
  "English",
  "Chinese",
  "Simplified Chinese",
  "Traditional Chinese",
  "Japanese",
  "Korean",
  "French",
  "German",
  "Spanish",
  "Portuguese",
  "Russian",
  "Italian",
  "Arabic",
  "Bengali",
  "Bulgarian",
  "Catalan",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "Estonian",
  "Finnish",
  "Greek",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Indonesian",
  "Latvian",
  "Lithuanian",
  "Malay",
  "Norwegian",
  "Persian",
  "Polish",
  "Romanian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Swedish",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
] as const;

export function normalizeLanguage(value: string, fallback: string) {
  return languages.includes(value as (typeof languages)[number])
    ? value
    : fallback;
}
