include_guard(GLOBAL)

option(RWKV7_FAST_V4_GC_SECTIONS "Enable section garbage collection to reduce binary size" ON)
option(RWKV7_FAST_V4_AUTO_STRIP "Strip release executables after linking when possible" ON)
option(RWKV7_FAST_BUILD_TESTS "Build unit tests" ON)
option(RWKV7_STATE_TUNING "Build the CUDA state-tuning backward sidecar" ON)
option(RWKV7_FAST_V4_MSVC_LTCG "Enable MSVC link-time code generation" OFF)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(RWKV_GPU_BACKEND STREQUAL "HIP")
  set(CMAKE_HIP_STANDARD 17)
  set(CMAKE_HIP_STANDARD_REQUIRED ON)
  set(CMAKE_HIP_EXTENSIONS OFF)
else()
  set(CMAKE_CUDA_STANDARD 17)
  set(CMAKE_CUDA_STANDARD_REQUIRED ON)
  set(CMAKE_CUDA_EXTENSIONS OFF)
  set(CMAKE_CUDA_RUNTIME_LIBRARY Shared)
endif()
