include_guard(GLOBAL)

if(RWKV_GPU_BACKEND STREQUAL "HIP")
  find_package(hip REQUIRED CONFIG)
  find_package(hipblas REQUIRED CONFIG)
  find_package(hipblaslt REQUIRED CONFIG)
  find_package(hiprand REQUIRED CONFIG)
else()
  find_package(CUDAToolkit REQUIRED)
endif()

find_package(SQLite3 REQUIRED)
find_package(Drogon CONFIG QUIET)
if(NOT Drogon_FOUND)
  find_package(Drogon QUIET)
endif()

# Normalize the SQLite target name across CMake and vcpkg variants.
if(TARGET SQLite3::SQLite3)
  set(RWKV_SQLITE_TARGET SQLite3::SQLite3)
elseif(TARGET SQLite::SQLite3)
  set(RWKV_SQLITE_TARGET SQLite::SQLite3)
else()
  add_library(rwkv_sqlite INTERFACE)
  if(SQLite3_INCLUDE_DIRS)
    target_include_directories(rwkv_sqlite INTERFACE ${SQLite3_INCLUDE_DIRS})
  endif()
  if(SQLite3_LIBRARIES)
    target_link_libraries(rwkv_sqlite INTERFACE ${SQLite3_LIBRARIES})
  elseif(SQLite3_LIBRARY)
    target_link_libraries(rwkv_sqlite INTERFACE ${SQLite3_LIBRARY})
  else()
    message(FATAL_ERROR "SQLite3 was found, but no linkable target or library variable was provided")
  endif()
  set(RWKV_SQLITE_TARGET rwkv_sqlite)
endif()
